# DualTF-FLSim default configuration

ray:
  num_cpus: 32
  num_gpus: 4
  ignore_reinit_error: true

resources:
  client:
    num_cpus: 4
    num_gpus: 1

simulation:
  num_clients: 24
  total_rounds: 1
  fraction_fit: 0.25
  fraction_evaluate: 0.0
  min_available_clients: 6
  min_fit_clients: 6

strategy:
  # Choose between 'scaffold' and 'fedprox'
  type: scaffold

training:
  local_epochs: 5
  lr: 1.0e-4
  proximal_mu: 0.0

model:
  # seq_len MUST equal data.seq_length
  seq_len: 75
  time:
    enc_in: 25
    c_out: 25
    e_layers: 3
    n_heads: 8
    d_model: 512
  freq:
    # nest_length is used for data grand-windowing and the freq model window size
    nest_length: 25
    enc_in: 25
    c_out: 25
    e_layers: 3
    n_heads: 4
    d_model: 512

data:
  dataset: PSM
  dirichlet_alpha: 0.5
  time_batch_size: 64
  freq_batch_size: 32
  # seq_length MUST equal model.seq_len
  seq_length: 75
  step: 1

evaluation:
  enabled: false
  min_consecutive: 10
  num_thresholds_periodic: 256
  num_thresholds_final: 1000
  seq_length: 50
  step: 5
  threshold_quantile_range: [0.01, 0.99]
  prefer_gpu_sweep: true

scaffold:
  damping: 0.1
  max_corr_norm: 1.0
  grad_clip: 1.0

post_training:
  generate_arrays: true
  dataset: PSM
  data_num: 0
  seq_length: 75
  nest_length: 25

wandb:
  enabled: true
  project: DualTF-FLSim
  entity: null      # optional
  run_name: null    # optional; autogenerated if null
  tags: [fl, dualtf, psm]
  notes: ""
